from .color_dot import ColorDot
from .workspace_tab import WorkspaceTab
from .help_tab import HelpTab
from .settings_tab import SettingsTab
from .command_worker import CommandWorker
from .razor_tab import RazorTab
from .profiling_tab import ProfilingTab
from .screenshots_tab import ScreenshotsTab
from .android_so_analysis_tab import AndroidSoAnalysisTab
from .battery_widget import BatteryWidget
from .theme import Theme
